name: bishop
version: 0.4.0
description: Bishop is a chess logic package with flexible variant support
homepage: https://github.com/alexobviously/bishop
environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  benchmark_harness: ^2.0.0
  collection: ^1.15.0
  lints: ^2.0.0
  test: ^1.17.10