name: squares
version: 0.1.0
description: Squares is a chess logic library with generic variant support
homepage: https://github.com/alexobviously/squares.dart
environment:
  sdk: '>=2.13.0-0 <3.0.0'

dev_dependencies:
  benchmark_harness: ^2.0.0
  test: ^1.17.10