name: Bishop Package Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  dart:latest

    steps:
      - uses: actions/checkout@v2

      - name: Print Dart SDK version
        run: dart --version

      - name: Install dependencies
        run: dart pub get
      
      - name: Run Perft tests
        run: dart test test/perft_test.dart

      - name: Run Validation tests
        run: dart test test/validation_test.dart
        
      - name: Run Comparison tests
        run: dart test test/comparison_test.dart

      - name: Run Draw tests
        run: dart test test/draw_test.dart
      
      - name: Run Piece tests
        run: dart test test/pieces_test.dart